# Generated by Django 2.2.26 on 2022-02-17 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='latest_update_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
